// <auto-generated />
namespace GigHubChMask2011.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddArtistName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddArtistName));
        
        string IMigrationMetadata.Id
        {
            get { return "201803221841328_AddArtistName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
